-- Part 2 of the 2026-08-30 redesign — uploaded photos.
--
-- `storage_key` is opaque to the database: it is generated by src/lib/storage.ts and
-- resolved by whichever driver is configured, so nothing here assumes a filesystem.
--
-- `listings.image_url` is deliberately NOT dropped in this migration. Fifteen production
-- files still read it; dropping it here would leave the tree broken until the last of
-- them is migrated. 0013 drops it once they are.

CREATE TABLE IF NOT EXISTS "listing_images" (
  "id" serial PRIMARY KEY NOT NULL,
  "listing_id" integer NOT NULL,
  "storage_key" text NOT NULL,
  "content_type" text NOT NULL,
  "byte_size" integer NOT NULL,
  "width" integer,
  "height" integer,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint
-- CASCADE, unlike categories' RESTRICT: an image has no meaning without its listing, and
-- orphaned rows would point at objects nothing will ever delete.
ALTER TABLE "listing_images"
  ADD CONSTRAINT "listing_images_listing_id_listings_id_fk"
  FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE;

--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "listing_images_listing_id_idx"
  ON "listing_images" ("listing_id", "sort_order");

--> statement-breakpoint
-- A listing exists before its photos do: the form creates it, uploads against its id,
-- then publishes. `draft` is that intermediate state, and it is excluded from every
-- public read path.
ALTER TYPE "listing_status" ADD VALUE IF NOT EXISTS 'draft';
