import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      // Raw <img> is allowed here -- next/image cannot serve our own /api/images route
      // without remote patterns for a same-origin path -- but it must be an explicit
      // decision, not something a warning count can quietly stop meaning anything for.
      // Every <img> gets an eslint-disable-next-line, no exceptions.
      "@next/next/no-img-element": "error",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` (C2C-QA-2); istanbul's HTML report
    // ships its own vendored scripts and is not ours to lint.
    "coverage/**",
  ]),
]);

export default eslintConfig;
